name: tikka
description: "A Clean Architecture implementation for Flutter apps that supports Bloc-based use cases, 
unidirectional data flow across all layers, and a specific design pattern for the Presentation layer. 
Implementation provides comprehensive support for every layer of the Clean Architecture paradigm."
version: 0.8.1
documentation: https://pub.dev/documentation/tikka/latest/
homepage: https://github.com/Boogie-Software/Tikka
repository: https://github.com/Boogie-Software/Tikka
issue_tracker: https://github.com/Boogie-Software/Tikka/issues
license: Apache-2.0

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  injector: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  test: ^1.24.3
  mockito: ^5.4.5
  bloc_test: ^10.0.0

flutter:

  # assets:


