// Mocks generated by Mockito 5.4.5 from annotations
// in tikka/test/tikka/presentation/presenter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i2;
import 'package:tikka/presentation/view_state.dart' as _i1;
import 'package:tikka/presentation/view_state_observer.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ViewStateObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewStateObserver<S extends _i1.ViewState> extends _i2.Mock
    implements _i3.ViewStateObserver<S> {
  MockViewStateObserver() {
    _i2.throwOnMissingStub(this);
  }

  @override
  void onViewStateChanged(S? state) => super.noSuchMethod(
    Invocation.method(#onViewStateChanged, [state]),
    returnValueForMissingStub: null,
  );
}
